# Generated by Django 5.2.12 on 2026-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('seen', 'Seen'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
